#################################################
planner:
  initial_epsilon: 100
  final_epsilon: 100
  decrement_epsilon: 0.2
  return_first_solution: false
  max_time: 15
  repair_time: -1

#################################################
cost_per_cell: 10
cost_per_meter: 500
cost_obstacle_dist: 0
max_obstacle_dist: 0.00
w_cell: 10
w_action: 0
w_smooth: 0

#################################################
env:
  use_bfs_heuristic: true
  attempt_shortcut: true
  interpolation_distance: 0.02
  planning_link_sphere_radius: 0.05
  field:
    size_x: 2.0
    size_y: 2.0
    size_z: 2.5
    origin_x: -0.5
    origin_y: -1.0
    origin_z: 0.0
    resolution: 0.02

#################################################
primitives:
  arm:
    joint_snap: true
    xyzrpy_snap: true
    rpy_snap: true
    joint_snap_thresh: 0.15
    xyzrgb_snap_thresh: 0.15
    simple:
     - [ [ 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [-8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, -8.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, 0.0, -8.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, 0.0, 0.0, -8.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [-4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, -4.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, -4.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, -4.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, -4.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, 0.0, -4.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -4.0], -1.0, 0.2]
  arm_with_torso:
    joint_snap: true
    xyzrpy_snap: true
    rpy_snap: true
    joint_snap_thresh: 0.15
    xyzrgb_snap_thresh: 0.15
    simple:
     - [ [ 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [-8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, -8.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, 0.0, -8.0, 0.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, 0.0, 0.0, -8.0, 0.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 8.0, 0.0, 0.0, 0.0], 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, -8.0, 0.0, 0.0, 0.0], 0.2]
     - [ [ 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [-4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, -4.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, -4.0, 0.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, -4.0, 0.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, -4.0, 0.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, 0.0, -4.0, 0.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0, 0.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -4.0, 0.0], -1.0, 0.2]
     - [ [ 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 4.0], -1.0, 0.2]
     - [ [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -4.0], -1.0, 0.2]

#################################################
visual:
  expanded_states: true
  field: true
